/* Pixel character frames. Generated; edit the grids freely: one char = one pixel, "." = transparent. */
window.USHNA_SPRITE = {
 "w": 20,
 "h": 28,
 "palette": {
  "K": "#2b1a20",
  "R": "#1e1c21",
  "r": "#3a3740",
  "Y": "#ffcd00",
  "W": "#ffffff",
  "G": "#d6aa28",
  "H": "#3b2418",
  "h": "#57392a",
  "S": "#d9a67a",
  "s": "#c48c62",
  "L": "#c96a7a",
  "P": "#f7f2f3",
  "p": "#ded2d6",
  "D": "#4a3440",
  "B": "#c97b94",
  "g": "#d47887"
 },
 "frames": {
  "idle": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRYYRRRRRK....",
   "....KRRRYYRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   ".KRRRRRRRRRRRRRRRRK.",
   ".KGGGGGGGGGGGGGGGGK.",
   "...KHHSSSSSSSSHHK...",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKWSSSKWSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHsSSLWWLSSsHHK..",
   "..KHHHsSSLLSSsHHHK..",
   "..KHHHHSSSSSSHHHHK..",
   "..KHHHHKSSSSKHHHHK..",
   "..KHHHKPpKKpPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDK......",
   "......KDDKKDDK......",
   ".....KBBK..KBBK.....",
   ".....KKKK..KKKK....."
  ],
  "blink": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRYYRRRRRK....",
   "....KRRRYYRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   ".KRRRRRRRRRRRRRRRRK.",
   ".KGGGGGGGGGGGGGGGGK.",
   "...KHHSSSSSSSSHHK...",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHsSSLWWLSSsHHK..",
   "..KHHHsSSLLSSsHHHK..",
   "..KHHHHSSSSSSHHHHK..",
   "..KHHHHKSSSSKHHHHK..",
   "..KHHHKPpKKpPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDK......",
   "......KDDKKDDK......",
   ".....KBBK..KBBK.....",
   ".....KKKK..KKKK....."
  ],
  "walk1": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRYYRRRRRK....",
   "....KRRRYYRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   ".KRRRRRRRRRRRRRRRRK.",
   ".KGGGGGGGGGGGGGGGGK.",
   "...KHHSSSSSSSSHHK...",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKWSSSKWSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHsSSLWWLSSsHHK..",
   "..KHHHsSSLLSSsHHHK..",
   "..KHHHHSSSSSSHHHHK..",
   "..KHHHHKSSSSKHHHHK..",
   "..KHHHKPpKKpPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   ".....KDDDDDDDK......",
   "....KDDKKKKDDK......",
   "...KBBK.....KBBK....",
   "...KKKK.....KKKK...."
  ],
  "walk2": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRYYRRRRRK....",
   "....KRRRYYRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   ".KRRRRRRRRRRRRRRRRK.",
   ".KGGGGGGGGGGGGGGGGK.",
   "...KHHSSSSSSSSHHK...",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKWSSSKWSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHsSSLWWLSSsHHK..",
   "..KHHHsSSLLSSsHHHK..",
   "..KHHHHSSSSSSHHHHK..",
   "..KHHHHKSSSSKHHHHK..",
   "..KHHHKPpKKpPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDDK.....",
   "......KDDKKKKDDK....",
   "....KBBK.....KBBK...",
   "....KKKK.....KKKK..."
  ],
  "cheer": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRYYRRRRRK....",
   "....KRRRYYRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   ".KRRRRRRRRRRRRRRRRK.",
   ".KGGGGGGGGGGGGGGGGK.",
   "...KHHSSSSSSSSHHK...",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSSKWSSSKWSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHsSSLWWLSSsHHK..",
   ".KKHHHsSLWWLSsHHHKK.",
   "KSKHHHHSSSSSSHHHHKSK",
   "KSKHHHHKSSSSKHHHHKSK",
   "KPKHHHKPpKKpPKHHHKPK",
   "KPKHHKPPPPPPPPKHHKPK",
   ".KKKHKPPPPPPPPKHKKK.",
   "...KKKKPPPPPPKKKK...",
   "....KKKpPPPPpKKK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDK......",
   "......KDDKKDDK......",
   ".....KBBK..KBBK.....",
   ".....KKKK..KKKK....."
  ],
  "oops": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRYYRRRRRK....",
   "....KRRRYYRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   ".KRRRRRRRRRRRRRRRRK.",
   ".KGGGGGGGGGGGGGGGGK.",
   "...KHHSSSSSSSSHHK...",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHSKSSSSSSKSHHK..",
   "..KHHSSKSSSSKSSHHK..",
   "..KHHSSKKSSSKKSHHK..",
   "..KHHSSSSSSSSSSHHK..",
   "..KHHsSSSKKSSSsHHK..",
   "..KHHHsSSKKSSsHHHK..",
   "..KHHHHSSSSSSHHHHK..",
   "..KHHHHKSSSSKHHHHK..",
   "..KHHHKPpKKpPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDK......",
   "......KDDKKDDK......",
   ".....KBBK..KBBK.....",
   ".....KKKK..KKKK....."
  ],
  "back": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRRRRRRRRK....",
   "....KRRRRRRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   "..KKRRRRRRRRRRRRKK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHhHHHHHHHHHhHK..",
   "..KHHHHhHHHHHhHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHhHHHHHHHHHHHK..",
   "..KHHHHHHHHhHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHhHHHHHHHhHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHKPPPPPPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDK......",
   "......KDDKKDDK......",
   ".....KBBK..KBBK.....",
   ".....KKKK..KKKK....."
  ],
  "backwalk1": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRRRRRRRRK....",
   "....KRRRRRRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   "..KKRRRRRRRRRRRRKK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHhHHHHHHHHHhHK..",
   "..KHHHHhHHHHHhHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHhHHHHHHHHHHHK..",
   "..KHHHHHHHHhHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHhHHHHHHHhHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHKPPPPPPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   ".....KDDDDDDDK......",
   "....KDDKKKKDDK......",
   "...KBBK.....KBBK....",
   "...KKKK.....KKKK...."
  ],
  "backwalk2": [
   "........KKKK........",
   "......KKrrrrKK......",
   ".....KRrRRRRRRK.....",
   "....KRRRRRRRRRRK....",
   "....KRRRRRRRRRRK....",
   "...KRRRRRRRRRRRRK...",
   "..KKRRRRRRRRRRRRKK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHhHHHHHHHHHhHK..",
   "..KHHHHhHHHHHhHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHhHHHHHHHHHHHK..",
   "..KHHHHHHHHhHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHhHHHHHHHhHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHHHHHHHHHHHHK..",
   "..KHHHKPPPPPPKHHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "..KHHKPPPPPPPPKHHK..",
   "...KKKKPPPPPPKKKK...",
   "....KSKpPPPPpKSK....",
   "....KKKDDDDDDKKK....",
   "......KDDDDDDDK.....",
   "......KDDKKKKDDK....",
   "....KBBK.....KBBK...",
   "....KKKK.....KKKK..."
  ]
 }
};
